services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ssa-core-bundle-app
    volumes:
      - .:/app
      - ./vendor:/app/vendor
    working_dir: /app
    tty: true
    stdin_open: true
